name: advanced_weather_app
description: "A new Flutter project."
#
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.4
  http: ^1.3.0
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^6.1.3
  provider: ^6.1.4
  geocoding: ^3.0.0
  permission_handler: ^12.0.0+1
  location: ^5.0.3
  cupertino_icons: ^1.0.8
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background1.jpeg
